### ISSUE TITLE
Any way to change the music style?

### ISSUE THREAD

**Issue by torizo237** [elhobbs/prboom3ds#24]
This isn't much of an issue but I'd like to know if it's possible to change the midi sound. I heavily dislike the default music style and want to change it to be as similar sounding as the original music style, which is fluidsynth I believe. 

Any way to do it?

**Comment by elhobbs** [comment]
Original dos doom style? Like isa adlib or soundblaster? Probably not. If you can point me at something that can be used given the very limited processing power and memory constraints on the 3ds then I can take a look.  
Personally I think it sounds fine as is.

**Comment by torizo237** [comment]
I know literally nothing of hardware/software audio design, but what about some of these types of music packs? http://sc55.duke4.net/games.php#doom

Also, my question was if there was a way that I can do so manually. Is the music hardcoded into the cfg? I've been trying to manually replace the default music type into some of the ones in the link but they never seem to change.

**Comment by elhobbs** [comment]
No it cannot be changed. It is essentially using the opl emulator from dosbox - taken from chocolate doom. 
The problem is that the ogg and mp3 decode is fairly cpu intensive for the 3ds processor. To get it to be usable you need to drop the bit rate down quite a bit - I doubt any of the files you linked to would be playable on the 3ds without doom running like a slideshow.

**Comment by torizo237** [comment]
Aww geez. So is this music type really the best and most compatible?

**Comment by elhobbs** [comment]
I think it is the only option currently
